name: "Release"
on:
  push:
    branches:
    - master
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: | 
          6.0.x
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build and zip backend
      run: |
        dotnet \
          publish \
          code/Server.AWS/Server.AWS.csproj \
          -c Release \
          -o .local/Publish;
        zip -r .local/Backend.zip .local/Publish deploy/templates/BackendLambda.yml;
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Automatic release ${{ github.run_number }}"
        files: |
          .local/Backend.zip
          